[package]
name = "cargo-test-all"
version = "0.1.0"
authors = ["Valeryi Savich <relrin78@gmail.com>"]
edition = "2018"

[dependencies]
cargo = "0.37.0"
cargo-clone = "0.1.3"
failure = "0.1.6"
rustc-serialize = "0.3"
structopt = "0.3.5"
structopt-derive = "0.3.5"
toml = "0.5"